import { flatpakRefs } from "./deck-apps";
import type { DeckConfig } from "./deck-config";
import { normalizeDeckConfig } from "./deck-config";

/**
 * Generate the on-device `provision.sh` for a Steam Deck, ported from the proven
 * v1 Ansible roles + `deck.sh` into a single native bash runner (no Ansible
 * dependency). The script is carried on the USB `BOOTIBLE` partition and run once
 * in Desktop Mode after install. SteamOS-safe by construction: requires a user
 * password, takes a btrfs snapshot first, installs only via Flatpak (--user,
 * survives updates), and allowlists any /etc change so a SteamOS update can't wipe it.
 *
 * This slice covers: base scaffold + Flatpak apps + SSH. Later slices append
 * Decky/Proton/EmuDeck/Tailscale/Sunshine/Waydroid blocks to the same script.
 */

const FLATHUB_REPO = "https://dl.flathub.org/repo/flathub.flatpakrepo";

const HEADER = `#!/usr/bin/env bash
# Generated by bootible — do not edit. Run once in Desktop Mode.
set -euo pipefail

say() { printf '\\n\\033[0;36m==>\\033[0m %s\\n' "$1"; }
ok()  { printf '\\033[0;32m  ok\\033[0m %s\\n' "$1"; }
warn(){ printf '\\033[1;33m  !!\\033[0m %s\\n' "$1"; }

say "bootible — provisioning this Steam Deck"

# A password is required for sudo. The 'deck' user has none by default.
if passwd -S "$USER" 2>/dev/null | grep -q " NP "; then
  warn "No password set for $USER. Run 'passwd' to set one, then re-run this script."
  exit 1
fi
sudo -v`;

const SNAPSHOT = `say "Taking a btrfs snapshot (rollback point)"
if findmnt -n -o FSTYPE / | grep -q btrfs; then
  SNAP="/.snapshots/pre-bootible-$(date +%Y%m%d-%H%M%S)"
  (
    trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
    sudo steamos-readonly disable 2>/dev/null || true
    sudo mkdir -p /.snapshots
    if sudo btrfs subvolume snapshot / "$SNAP" 2>/dev/null; then
      ok "snapshot: $SNAP"
    else
      warn "snapshot skipped (no root subvolume)"
    fi
  )
else
  warn "root is not btrfs — skipping snapshot"
fi`;

const FLATHUB = `say "Ensuring Flathub is configured"
flatpak remote-add --if-not-exists --user flathub ${FLATHUB_REPO}
ok "flathub ready"`;

/** sudo-write a file via tee, toggling the read-only rootfs around it. */
function rwWrite(path: string, content: string, append = false): string {
  const op = append ? "tee -a" : "tee";
  return `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo install -d "$(dirname ${path})"
  sudo ${op} ${path} >/dev/null <<'BOOTIBLE_EOF'
${content}
BOOTIBLE_EOF
)`;
}

function flatpakBlock(cfg: DeckConfig): string {
  const refs = flatpakRefs(cfg.flatpakApps);
  if (refs.length === 0) return "";
  const installs = refs
    .map(
      (ref) =>
        `flatpak install --user --noninteractive --or-update flathub ${ref} || warn "failed: ${ref}"`,
    )
    .join("\n");
  return `say "Installing ${refs.length} Flatpak app(s)"
${installs}
ok "flatpak apps done"`;
}

function sshBlock(cfg: DeckConfig): string {
  if (!cfg.ssh.enabled) return "";
  const lines = [`say "Enabling SSH"`, `sudo systemctl enable --now sshd`];

  if (cfg.ssh.port !== 22) {
    // Change the port AND allowlist it so a SteamOS update doesn't revert it.
    lines.push(
      `say "Setting SSH port ${cfg.ssh.port}"`,
      `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo sed -i -E 's/^#?Port .*/Port ${cfg.ssh.port}/' /etc/ssh/sshd_config
  grep -q '^Port ${cfg.ssh.port}' /etc/ssh/sshd_config || echo 'Port ${cfg.ssh.port}' | sudo tee -a /etc/ssh/sshd_config >/dev/null
)`,
      // Persist across SteamOS atomic updates (3.6+).
      rwWrite("/etc/atomic-update.conf.d/bootible-ssh.conf", "/etc/ssh/sshd_config"),
      `sudo systemctl restart sshd`,
    );
  }

  if (cfg.ssh.authorizedKeys.length > 0) {
    const keys = cfg.ssh.authorizedKeys.join("\n");
    lines.push(
      `say "Authorising ${cfg.ssh.authorizedKeys.length} SSH key(s)"`,
      `install -d -m 700 "$HOME/.ssh"`,
      `cat > "$HOME/.ssh/authorized_keys" <<'BOOTIBLE_KEYS'
# Managed by bootible
${keys}
BOOTIBLE_KEYS`,
      `chmod 600 "$HOME/.ssh/authorized_keys"`,
    );
  }
  lines.push(`ok "ssh ready"`);
  return lines.join("\n");
}

export function generateDeckProvision(input: Partial<DeckConfig>): string {
  const cfg = normalizeDeckConfig(input);
  const blocks: string[] = [HEADER];

  if (cfg.createSnapshot) blocks.push(SNAPSHOT);
  if (cfg.hostname) {
    blocks.push(`say "Setting hostname ${cfg.hostname}"
sudo hostnamectl set-hostname ${JSON.stringify(cfg.hostname)}`);
  }
  blocks.push(FLATHUB);

  const fp = flatpakBlock(cfg);
  if (fp) blocks.push(fp);
  const ssh = sshBlock(cfg);
  if (ssh) blocks.push(ssh);

  blocks.push(`say "Done. Restart to Gaming Mode to see your apps."`);
  return `${blocks.join("\n\n")}\n`;
}
