import { BEACON_PORT } from "./beacon";
import { flatpakRefs, passwordManagers } from "./deck-apps";
import type { DeckConfig } from "./deck-config";
import { normalizeDeckConfig } from "./deck-config";

/**
 * Generate the on-device `provision.sh` for a Steam Deck, ported from the proven
 * v1 Ansible roles + `deck.sh` into a single native bash runner (no Ansible
 * dependency). The script is carried on the USB `BOOTIBLE` partition and run once
 * in Desktop Mode after install. SteamOS-safe by construction: requires a user
 * password, takes a btrfs snapshot first, installs only via Flatpak (--user,
 * survives updates), and allowlists any /etc change so a SteamOS update can't wipe it.
 *
 * Covers the full v1 payload: base scaffold, Flatpak apps, SSH, Decky + plugins,
 * Proton tools (GE/ProtonUp-Qt/protontricks), EmuDeck staging, Sunshine/VNC,
 * Tailscale, Waydroid staging, StickDeck, and password managers (Flatpak or
 * Distrobox). JSON parsing + unzip use python3, which is always present on SteamOS.
 */

const FLATHUB_REPO = "https://dl.flathub.org/repo/flathub.flatpakrepo";

const HEADER = `#!/usr/bin/env bash
# Generated by bootible — do not edit. Run once in Desktop Mode.
set -euo pipefail

# Record the whole run so it's auditable over SSH afterwards (bootible reads these
# to confirm every app installed): ~/.bootible/provision.log = full transcript;
# ~/.bootible/receipt = one line per milestone (ok) / problem (WARN).
BOOTIBLE_DIR="$HOME/.bootible"
mkdir -p "$BOOTIBLE_DIR"
BOOTIBLE_RECEIPT="$BOOTIBLE_DIR/receipt"
: > "$BOOTIBLE_DIR/provision.log"
: > "$BOOTIBLE_RECEIPT"
exec > >(tee -a "$BOOTIBLE_DIR/provision.log") 2>&1

say() { printf '\\n\\033[0;36m==>\\033[0m %s\\n' "$1"; }
ok()  { printf '\\033[0;32m  ok\\033[0m %s\\n' "$1"; printf 'ok   %s\\n' "$1" >> "$BOOTIBLE_RECEIPT"; }
warn(){ printf '\\033[1;33m  !!\\033[0m %s\\n' "$1"; printf 'WARN %s\\n' "$1" >> "$BOOTIBLE_RECEIPT"; }

say "bootible — provisioning this Steam Deck"

# A password is required for sudo. The 'deck' user has none by default.
if passwd -S "$USER" 2>/dev/null | grep -q " NP "; then
  warn "No password set for $USER. Run 'passwd' to set one, then re-run this script."
  exit 1
fi
sudo -v`;

const SNAPSHOT = `say "Taking a btrfs snapshot (rollback point)"
if findmnt -n -o FSTYPE / | grep -q btrfs; then
  SNAP="/.snapshots/pre-bootible-$(date +%Y%m%d-%H%M%S)"
  (
    trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
    sudo steamos-readonly disable 2>/dev/null || true
    sudo mkdir -p /.snapshots
    if sudo btrfs subvolume snapshot / "$SNAP" 2>/dev/null; then
      ok "snapshot: $SNAP"
    else
      warn "snapshot skipped (no root subvolume)"
    fi
  )
else
  warn "root is not btrfs — skipping snapshot"
fi`;

const FLATHUB = `say "Ensuring Flathub is configured"
flatpak remote-add --if-not-exists --user flathub ${FLATHUB_REPO}
ok "flathub ready"`;

/** sudo-write a file via tee, toggling the read-only rootfs around it. */
function rwWrite(path: string, content: string, append = false): string {
  const op = append ? "tee -a" : "tee";
  return `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo install -d "$(dirname ${path})"
  sudo ${op} ${path} >/dev/null <<'BOOTIBLE_EOF'
${content}
BOOTIBLE_EOF
)`;
}

function flatpakBlock(cfg: DeckConfig): string {
  const refs = flatpakRefs(cfg.flatpakApps);
  if (refs.length === 0) return "";
  return `say "Installing ${refs.length} Flatpak app(s)"
${refs.map(fpInstall).join("\n")}
ok "flatpak apps done"`;
}

function sshBlock(cfg: DeckConfig): string {
  if (!cfg.ssh.enabled) return "";
  const lines = [`say "Enabling SSH"`, `sudo systemctl enable --now sshd`];

  if (cfg.ssh.port !== 22) {
    // Change the port AND allowlist it so a SteamOS update doesn't revert it.
    lines.push(
      `say "Setting SSH port ${cfg.ssh.port}"`,
      `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo sed -i -E 's/^#?Port .*/Port ${cfg.ssh.port}/' /etc/ssh/sshd_config
  grep -q '^Port ${cfg.ssh.port}' /etc/ssh/sshd_config || echo 'Port ${cfg.ssh.port}' | sudo tee -a /etc/ssh/sshd_config >/dev/null
)`,
      // Persist across SteamOS atomic updates (3.6+).
      rwWrite("/etc/atomic-update.conf.d/bootible-ssh.conf", "/etc/ssh/sshd_config"),
      `sudo systemctl restart sshd`,
    );
  }

  const ghUser = cfg.ssh.githubUser;
  if (cfg.ssh.authorizedKeys.length > 0 || ghUser) {
    lines.push(`install -d -m 700 "$HOME/.ssh"`);
    if (cfg.ssh.authorizedKeys.length > 0) {
      const keys = cfg.ssh.authorizedKeys.join("\n");
      lines.push(
        `say "Authorising ${cfg.ssh.authorizedKeys.length} SSH key(s)"`,
        `cat > "$HOME/.ssh/authorized_keys" <<'BOOTIBLE_KEYS'
# Managed by bootible
${keys}
BOOTIBLE_KEYS`,
      );
    } else {
      // Start the file fresh so a re-run stays idempotent before appending below.
      lines.push(`printf '# Managed by bootible\\n' > "$HOME/.ssh/authorized_keys"`);
    }
    if (ghUser) {
      // Fetch the user's public keys on-device (same mechanism as the ROG flow).
      lines.push(
        `say "Fetching SSH keys from github.com/${ghUser}"`,
        `curl -fsSL "https://github.com/${ghUser}.keys" >> "$HOME/.ssh/authorized_keys" 2>/dev/null && ok "added github.com/${ghUser} keys" || warn "couldn't fetch github.com/${ghUser}.keys"`,
      );
    }
    lines.push(`chmod 600 "$HOME/.ssh/authorized_keys"`);
  }
  lines.push(`ok "ssh ready"`);
  return lines.join("\n");
}

const fpInstall = (ref: string) =>
  `flatpak install --user --noninteractive --or-update flathub ${ref} || warn "failed: ${ref}"`;

function deckyBlock(cfg: DeckConfig): string {
  if (!cfg.decky.enabled) return "";
  const lines = [
    `say "Installing Decky Loader"`,
    `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh || warn "decky install failed"`,
    // The plugin_loader service runs as root and owns ~/homebrew/plugins, so the
    // plugins dir is root-owned — ensure it with sudo (a plain mkdir as deck fails).
    `sudo mkdir -p "$HOME/homebrew/plugins"`,
  ];
  // plugins are store names (live-pulled by the app); resolve each to its latest
  // hash via the Decky store, download + extract, then RESTART the loader so the
  // plugins actually register (the missing step that broke manual installs in v1).
  const names = cfg.decky.plugins;
  if (names.length > 0) {
    // Single-quote-escape each store name — a manual `\"` escape doesn't stop
    // $()/backtick expansion, and names can arrive from an imported profile.
    const arr = names.map((n) => shq(n)).join(" ");
    lines.push(
      `say "Installing ${names.length} Decky plugin(s)"`,
      // Stop the loader first so no plugin's backend binary is running — otherwise
      // re-extracting over a live plugin hits ETXTBSY (caught re-running on hw).
      `sudo systemctl stop plugin_loader 2>/dev/null || true`,
      `STORE="$(curl -fsSL https://plugins.deckbrew.xyz/plugins || echo '[]')"`,
      `for NAME in ${arr}; do`,
      `  HASH="$(printf '%s' "$STORE" | N="$NAME" python3 -c "import sys,json,os; d=json.load(sys.stdin); p=next((x for x in d if x.get('name')==os.environ['N']),None); print(p['versions'][0]['hash'] if p and p.get('versions') else '')" 2>/dev/null || echo "")"`,
      `  if [ -z "$HASH" ]; then warn "plugin not found: $NAME"; continue; fi`,
      `  curl -fsSL "https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/$HASH.zip" -o /tmp/decky-plugin.zip && \\`,
      // extract as root (the plugins dir is root-owned); chown back to deck after.
      `    sudo python3 -m zipfile -e /tmp/decky-plugin.zip "$HOME/homebrew/plugins/" && ok "plugin: $NAME" || warn "plugin failed: $NAME"`,
      `done`,
      `rm -f /tmp/decky-plugin.zip`,
      `sudo chown -R "$USER:$USER" "$HOME/homebrew/plugins" 2>/dev/null || true`,
      `sudo systemctl restart plugin_loader 2>/dev/null || true`,
    );
  }
  lines.push(`ok "decky ready (restart Steam to see it)"`);
  return lines.join("\n");
}

function protonBlock(cfg: DeckConfig): string {
  const lines: string[] = [];
  if (cfg.proton.protonUpQt || cfg.proton.protontricks || cfg.proton.ge)
    lines.push(`say "Proton tools"`);
  if (cfg.proton.protonUpQt) lines.push(fpInstall("net.davidotek.pupgui2"));
  if (cfg.proton.protontricks) lines.push(fpInstall("com.github.Matoking.protontricks"));
  if (cfg.proton.ge) {
    lines.push(
      `say "Installing latest Proton-GE"`,
      `install -d "$HOME/.steam/root/compatibilitytools.d"`,
      // The Deck/Ally are x86_64; GE-Proton now also ships an aarch64 tarball, so
      // exclude ARM builds or we grab the wrong arch (caught on hardware, 29 Jun).
      `GE_URL="$(curl -fsSL https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | python3 -c "import sys,json; d=json.load(sys.stdin); print(next((a['browser_download_url'] for a in d.get('assets',[]) if a['name'].endswith('.tar.gz') and 'aarch64' not in a['name'] and 'arm64' not in a['name']),''))" 2>/dev/null)"`,
      `if [ -n "$GE_URL" ]; then`,
      `  curl -fsSL "$GE_URL" -o /tmp/proton-ge.tar.gz && \\`,
      `    tar -xzf /tmp/proton-ge.tar.gz -C "$HOME/.steam/root/compatibilitytools.d/" && ok "Proton-GE installed" || warn "Proton-GE extract failed"`,
      `  rm -f /tmp/proton-ge.tar.gz`,
      `else warn "Proton-GE: use ProtonUp-Qt (release lookup failed)"; fi`,
    );
  }
  return lines.join("\n");
}

function emudeckBlock(cfg: DeckConfig): string {
  if (!cfg.emudeck) return "";
  // auto/internal → ~/Emulation; sdcard → the first SD mount if present.
  const path =
    cfg.emulationStorage === "sdcard" ? `\${SDCARD:-$HOME/Emulation}` : `$HOME/Emulation`;
  return `say "Staging EmuDeck"
SDCARD="$(ls -d /run/media/*/* 2>/dev/null | head -1)"
EMU="${path}"
for d in roms bios saves states; do install -d "$EMU/$d"; done
install -d "$HOME/Desktop"
curl -fsSL https://www.emudeck.com/EmuDeck.desktop -o "$HOME/Desktop/EmuDeck.desktop" && chmod +x "$HOME/Desktop/EmuDeck.desktop" || warn "EmuDeck download failed"
ok "EmuDeck staged at $EMU — run the wizard from Desktop"`;
}

/** Single-quote a value for safe embedding in the generated bash. */
function shq(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function streamingBlock(cfg: DeckConfig): string {
  const lines: string[] = [];
  if (cfg.sunshine.enabled || cfg.vnc) lines.push(`say "Streaming / remote"`);
  if (cfg.sunshine.enabled) {
    lines.push(fpInstall("dev.lizardbyte.app.Sunshine"));
    // Pre-set the web-UI credentials (`sunshine --creds <user> <pass>`).
    if (cfg.sunshine.user && cfg.sunshine.promptPass) {
      // Password kept OFF the USB — prompt for it here, on-device, instead.
      lines.push(`printf '\\nSunshine password for %s: ' ${shq(cfg.sunshine.user)}`);
      lines.push("read -rs _sunpass || true; echo");
      lines.push(
        `flatpak run dev.lizardbyte.app.Sunshine --creds ${shq(cfg.sunshine.user)} "$_sunpass" 2>/dev/null && ok "Sunshine credentials set" || warn "set Sunshine creds at https://localhost:47990"`,
      );
      lines.push("unset _sunpass");
    } else if (cfg.sunshine.user && cfg.sunshine.pass) {
      lines.push(
        `flatpak run dev.lizardbyte.app.Sunshine --creds ${shq(cfg.sunshine.user)} ${shq(cfg.sunshine.pass)} 2>/dev/null && ok "Sunshine credentials set" || warn "set Sunshine creds at https://localhost:47990"`,
      );
    }
  }
  if (cfg.vnc) lines.push(fpInstall("org.tigervnc.vncviewer"));
  return lines.join("\n");
}

function tailscaleBlock(cfg: DeckConfig): string {
  if (!cfg.tailscale) return "";
  // The generic tailscale.com/install.sh refuses on SteamOS (immutable /usr). The
  // official Deck method is the deck-tailscale installer (systemd-sysext overlay
  // into /var, survives SteamOS updates). `tailscale up` stays interactive (QR auth).
  return `say "Installing Tailscale"
if command -v tailscale >/dev/null 2>&1; then
  ok "Tailscale already installed — run 'tailscale up' to log in"
else
  rm -rf "$HOME/deck-tailscale"
  if git clone --depth 1 https://github.com/tailscale-dev/deck-tailscale.git "$HOME/deck-tailscale" >/dev/null 2>&1 && sudo bash "$HOME/deck-tailscale/tailscale.sh" >/dev/null 2>&1; then
    ok "Tailscale installed — run 'tailscale up' to log in"
  else
    warn "Tailscale install failed — install manually: https://github.com/tailscale-dev/deck-tailscale"
  fi
fi`;
}

function networkBlock(cfg: DeckConfig): string {
  const s = cfg.staticIp;
  if (!s) return "";
  const nmType = s.iface === "ethernet" ? "802-3-ethernet" : "802-11-wireless";
  const label = s.iface === "ethernet" ? "Ethernet" : "Wi-Fi";
  const props = [
    `ipv4.method manual`,
    `ipv4.addresses ${shq(`${s.ip}/${s.prefix}`)}`,
    s.gateway ? `ipv4.gateway ${shq(s.gateway)}` : "",
    s.dns ? `ipv4.dns ${shq(s.dns)}` : "",
  ]
    .filter(Boolean)
    .join(" ");
  // Find the NetworkManager connection of the chosen type and pin it. Skips
  // cleanly if no such connection exists yet (e.g. undocked, no Ethernet).
  return `say "Setting a static IP on ${label}"
CON=$(nmcli -t -f NAME,TYPE connection show | awk -F: '$2=="${nmType}"{print $1; exit}')
if [ -n "$CON" ]; then
  sudo nmcli connection modify "$CON" ${props}
  sudo nmcli connection up "$CON" >/dev/null 2>&1 || warn "couldn't reapply $CON"
  ok "static IP ${s.ip}/${s.prefix} set on $CON"
else
  warn "no ${label} connection found — skipping static IP"
fi`;
}

function waydroidBlock(cfg: DeckConfig): string {
  if (!cfg.waydroid) return "";
  return `say "Staging Waydroid installer"
install -d "$HOME/Applications" "$HOME/Desktop"
if [ ! -x /usr/bin/waydroid ]; then
  git clone --depth 1 https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer.git "$HOME/Applications/SteamOS-Waydroid-Installer" 2>/dev/null || (cd "$HOME/Applications/SteamOS-Waydroid-Installer" && git pull) || warn "waydroid clone failed"
  cat > "$HOME/Desktop/Waydroid Installer.desktop" <<'BOOTIBLE_WD'
[Desktop Entry]
Name=Waydroid Installer
Exec=$HOME/Applications/SteamOS-Waydroid-Installer/steamos-waydroid-installer.sh
Terminal=true
Type=Application
Categories=System;
BOOTIBLE_WD
  chmod +x "$HOME/Desktop/Waydroid Installer.desktop"
fi
ok "Waydroid installer staged — run it from Desktop"`;
}

function stickdeckBlock(cfg: DeckConfig): string {
  if (!cfg.stickdeck) return "";
  // Release assets are stickdeck-vX.zip (Deck) + stickdeck-win-vX.zip (Windows) —
  // pick the non-Windows .zip (NOT one matching "linux"; the old filter found nothing).
  // It's a .zip (unzip via python3), and the Deck binary is run via launch.sh.
  return `say "Installing StickDeck"
install -d "$HOME/Applications/stickdeck" "$HOME/Desktop"
SD_URL="$(curl -fsSL https://api.github.com/repos/DiscreteTom/stickdeck-rs/releases/latest | python3 -c "import sys,json; d=json.load(sys.stdin); print(next((a['browser_download_url'] for a in d.get('assets',[]) if a['name'].lower().endswith('.zip') and 'win' not in a['name'].lower()),''))" 2>/dev/null)"
if [ -n "$SD_URL" ]; then
  if curl -fsSL "$SD_URL" -o /tmp/stickdeck.zip && python3 -c "import zipfile,sys; zipfile.ZipFile('/tmp/stickdeck.zip').extractall(sys.argv[1])" "$HOME/Applications/stickdeck"; then
    SD_LAUNCH="$(find "$HOME/Applications/stickdeck" -name launch.sh -type f | head -1)"
    [ -n "$SD_LAUNCH" ] && chmod +x "$SD_LAUNCH"
    cat > "$HOME/Desktop/StickDeck.desktop" <<BOOTIBLE_SD
[Desktop Entry]
Name=StickDeck
Exec=\${SD_LAUNCH:-$HOME/Applications/stickdeck/launch.sh}
Path=$HOME/Applications/stickdeck
Terminal=true
Type=Application
Categories=Game;Utility;
BOOTIBLE_SD
    chmod +x "$HOME/Desktop/StickDeck.desktop"
    ok "StickDeck installed"
  else warn "StickDeck extract failed"; fi
  rm -f /tmp/stickdeck.zip
else warn "StickDeck: release lookup failed"; fi`;
}

function passwordManagerBlock(cfg: DeckConfig): string {
  const pms = passwordManagers(cfg.passwordManagers.managers);
  if (pms.length === 0) return "";

  if (cfg.passwordManagers.method === "flatpak") {
    const lines = [`say "Password managers (Flatpak)"`];
    for (const pm of pms) {
      lines.push(
        pm.flatpakIsRef
          ? `flatpak install --user --noninteractive ${pm.flatpak} || warn "failed: ${pm.id}"`
          : fpInstall(pm.flatpak),
      );
    }
    return lines.join("\n");
  }

  // Distrobox: full-feature native installs in an Arch container.
  const lines = [
    `say "Password managers (Distrobox Arch container)"`,
    `if command -v distrobox >/dev/null 2>&1; then`,
    `  distrobox list --no-color 2>/dev/null | grep -q '| arch ' || distrobox create -i archlinux:latest -n arch --yes`,
    `  distrobox enter arch -- sudo pacman -S --needed --noconfirm base-devel git || warn "base-devel failed"`,
    `  distrobox enter arch -- bash -c 'command -v yay >/dev/null || (git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin && cd /tmp/yay-bin && makepkg -si --noconfirm)' || warn "yay failed"`,
  ];
  for (const pm of pms) {
    const inst = pm.aur ? `yay -S --noconfirm ${pm.pkg}` : `sudo pacman -S --noconfirm ${pm.pkg}`;
    lines.push(
      `  distrobox enter arch -- ${inst} || warn "pm failed: ${pm.id}"`,
      `  distrobox enter arch -- distrobox-export --app ${pm.bin} 2>/dev/null || true`,
    );
  }
  lines.push(`else warn "distrobox not found — skipping password managers"; fi`);
  return lines.join("\n");
}

/**
 * The end-of-provision beacon — mirrors the ROG `beaconBody` in strip.ts, but in
 * bash via python3 (always present on SteamOS). Once provision.sh finishes it
 * broadcasts {bootible:1, buildId, ip, hostname, username, status:"done"} on
 * BEACON_PORT every 5s for ~10 min, so the desktop's "Watch" screen discovers
 * this exact Deck (matched by buildId) with no IP hunting. Runs detached (nohup
 * &) so it keeps reporting after the script returns, and is bounded so it isn't a
 * permanent agent. Only emitted when the writer baked a buildId in.
 */
function beaconBlock(cfg: DeckConfig): string {
  if (!cfg.buildId) return "";
  // buildId + port + user cross as argv (NOT interpolated into the python source),
  // so a hostile value can't break out. The heredoc is single-quoted → the python
  // body is literal; only the argv on the command line is shell-expanded.
  return `say "Reporting back to bootible on your PC"
nohup python3 - ${shq(cfg.buildId)} ${BEACON_PORT} "$USER" >/dev/null 2>&1 <<'BOOTIBLE_BEACON' &
import sys, socket, time, json
build_id = sys.argv[1]
port = int(sys.argv[2])
username = sys.argv[3] if len(sys.argv) > 3 else ''
hostname = socket.gethostname()
def local_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return ''
for _ in range(120):
    payload = json.dumps({'bootible': 1, 'buildId': build_id, 'ip': local_ip(), 'hostname': hostname, 'username': username, 'status': 'done'})
    try:
        u = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        u.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        u.sendto(payload.encode(), ('255.255.255.255', port))
        u.close()
    except Exception:
        pass
    time.sleep(5)
BOOTIBLE_BEACON
ok "this Deck will report 'done' to bootible for ~10 min — open Watch on your PC"`;
}

export function generateDeckProvision(input: Partial<DeckConfig>): string {
  const cfg = normalizeDeckConfig(input);
  const blocks: string[] = [HEADER];

  if (cfg.createSnapshot) blocks.push(SNAPSHOT);
  if (cfg.hostname) {
    // shq() both — JSON.stringify is a JSON escape, not a bash one ($()/backticks
    // still expand inside its double quotes. (hostname is also sanitized upstream.)
    blocks.push(`say ${shq(`Setting hostname ${cfg.hostname}`)}
sudo hostnamectl set-hostname ${shq(cfg.hostname)}`);
  }
  blocks.push(FLATHUB);

  for (const block of [
    flatpakBlock(cfg),
    deckyBlock(cfg),
    protonBlock(cfg),
    emudeckBlock(cfg),
    streamingBlock(cfg),
    tailscaleBlock(cfg),
    networkBlock(cfg),
    sshBlock(cfg),
    passwordManagerBlock(cfg),
    stickdeckBlock(cfg),
    waydroidBlock(cfg),
    beaconBlock(cfg),
  ]) {
    if (block) blocks.push(block);
  }

  blocks.push(`WARN_COUNT="$(grep -c '^WARN' "$BOOTIBLE_RECEIPT" 2>/dev/null || true)"
printf 'DONE provision finished; %s warning(s)\\n' "$WARN_COUNT" >> "$BOOTIBLE_RECEIPT"
if [ "\${WARN_COUNT:-0}" -gt 0 ]; then
  warn "$WARN_COUNT step(s) had warnings — see ~/.bootible/receipt"
else
  ok "all steps completed cleanly"
fi
say "Done. Restart to Gaming Mode to see your apps + Decky."`);
  return `${blocks.join("\n\n")}\n`;
}
