import { flatpakRefs, passwordManagers } from "./deck-apps";
import type { DeckConfig } from "./deck-config";
import { normalizeDeckConfig } from "./deck-config";

/**
 * Generate the on-device `provision.sh` for a Steam Deck, ported from the proven
 * v1 Ansible roles + `deck.sh` into a single native bash runner (no Ansible
 * dependency). The script is carried on the USB `BOOTIBLE` partition and run once
 * in Desktop Mode after install. SteamOS-safe by construction: requires a user
 * password, takes a btrfs snapshot first, installs only via Flatpak (--user,
 * survives updates), and allowlists any /etc change so a SteamOS update can't wipe it.
 *
 * Covers the full v1 payload: base scaffold, Flatpak apps, SSH, Decky + plugins,
 * Proton tools (GE/ProtonUp-Qt/protontricks), EmuDeck staging, Sunshine/VNC,
 * Tailscale, Waydroid staging, StickDeck, and password managers (Flatpak or
 * Distrobox). JSON parsing + unzip use python3, which is always present on SteamOS.
 */

const FLATHUB_REPO = "https://dl.flathub.org/repo/flathub.flatpakrepo";

const HEADER = `#!/usr/bin/env bash
# Generated by bootible — do not edit. Run once in Desktop Mode.
set -euo pipefail

say() { printf '\\n\\033[0;36m==>\\033[0m %s\\n' "$1"; }
ok()  { printf '\\033[0;32m  ok\\033[0m %s\\n' "$1"; }
warn(){ printf '\\033[1;33m  !!\\033[0m %s\\n' "$1"; }

say "bootible — provisioning this Steam Deck"

# A password is required for sudo. The 'deck' user has none by default.
if passwd -S "$USER" 2>/dev/null | grep -q " NP "; then
  warn "No password set for $USER. Run 'passwd' to set one, then re-run this script."
  exit 1
fi
sudo -v`;

const SNAPSHOT = `say "Taking a btrfs snapshot (rollback point)"
if findmnt -n -o FSTYPE / | grep -q btrfs; then
  SNAP="/.snapshots/pre-bootible-$(date +%Y%m%d-%H%M%S)"
  (
    trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
    sudo steamos-readonly disable 2>/dev/null || true
    sudo mkdir -p /.snapshots
    if sudo btrfs subvolume snapshot / "$SNAP" 2>/dev/null; then
      ok "snapshot: $SNAP"
    else
      warn "snapshot skipped (no root subvolume)"
    fi
  )
else
  warn "root is not btrfs — skipping snapshot"
fi`;

const FLATHUB = `say "Ensuring Flathub is configured"
flatpak remote-add --if-not-exists --user flathub ${FLATHUB_REPO}
ok "flathub ready"`;

/** sudo-write a file via tee, toggling the read-only rootfs around it. */
function rwWrite(path: string, content: string, append = false): string {
  const op = append ? "tee -a" : "tee";
  return `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo install -d "$(dirname ${path})"
  sudo ${op} ${path} >/dev/null <<'BOOTIBLE_EOF'
${content}
BOOTIBLE_EOF
)`;
}

function flatpakBlock(cfg: DeckConfig): string {
  const refs = flatpakRefs(cfg.flatpakApps);
  if (refs.length === 0) return "";
  return `say "Installing ${refs.length} Flatpak app(s)"
${refs.map(fpInstall).join("\n")}
ok "flatpak apps done"`;
}

function sshBlock(cfg: DeckConfig): string {
  if (!cfg.ssh.enabled) return "";
  const lines = [`say "Enabling SSH"`, `sudo systemctl enable --now sshd`];

  if (cfg.ssh.port !== 22) {
    // Change the port AND allowlist it so a SteamOS update doesn't revert it.
    lines.push(
      `say "Setting SSH port ${cfg.ssh.port}"`,
      `(
  trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
  sudo steamos-readonly disable 2>/dev/null || true
  sudo sed -i -E 's/^#?Port .*/Port ${cfg.ssh.port}/' /etc/ssh/sshd_config
  grep -q '^Port ${cfg.ssh.port}' /etc/ssh/sshd_config || echo 'Port ${cfg.ssh.port}' | sudo tee -a /etc/ssh/sshd_config >/dev/null
)`,
      // Persist across SteamOS atomic updates (3.6+).
      rwWrite("/etc/atomic-update.conf.d/bootible-ssh.conf", "/etc/ssh/sshd_config"),
      `sudo systemctl restart sshd`,
    );
  }

  if (cfg.ssh.authorizedKeys.length > 0) {
    const keys = cfg.ssh.authorizedKeys.join("\n");
    lines.push(
      `say "Authorising ${cfg.ssh.authorizedKeys.length} SSH key(s)"`,
      `install -d -m 700 "$HOME/.ssh"`,
      `cat > "$HOME/.ssh/authorized_keys" <<'BOOTIBLE_KEYS'
# Managed by bootible
${keys}
BOOTIBLE_KEYS`,
      `chmod 600 "$HOME/.ssh/authorized_keys"`,
    );
  }
  lines.push(`ok "ssh ready"`);
  return lines.join("\n");
}

const fpInstall = (ref: string) =>
  `flatpak install --user --noninteractive --or-update flathub ${ref} || warn "failed: ${ref}"`;

function deckyBlock(cfg: DeckConfig): string {
  if (!cfg.decky.enabled) return "";
  const lines = [
    `say "Installing Decky Loader"`,
    `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh || warn "decky install failed"`,
    // The plugin_loader service runs as root and owns ~/homebrew/plugins, so the
    // plugins dir is root-owned — ensure it with sudo (a plain mkdir as deck fails).
    `sudo mkdir -p "$HOME/homebrew/plugins"`,
  ];
  // plugins are store names (live-pulled by the app); resolve each to its latest
  // hash via the Decky store, download + extract, then RESTART the loader so the
  // plugins actually register (the missing step that broke manual installs in v1).
  const names = cfg.decky.plugins;
  if (names.length > 0) {
    const arr = names.map((n) => `"${n.replace(/"/g, '\\"')}"`).join(" ");
    lines.push(
      `say "Installing ${names.length} Decky plugin(s)"`,
      // Stop the loader first so no plugin's backend binary is running — otherwise
      // re-extracting over a live plugin hits ETXTBSY (caught re-running on hw).
      `sudo systemctl stop plugin_loader 2>/dev/null || true`,
      `STORE="$(curl -fsSL https://plugins.deckbrew.xyz/plugins || echo '[]')"`,
      `for NAME in ${arr}; do`,
      `  HASH="$(printf '%s' "$STORE" | N="$NAME" python3 -c "import sys,json,os; d=json.load(sys.stdin); p=next((x for x in d if x.get('name')==os.environ['N']),None); print(p['versions'][0]['hash'] if p and p.get('versions') else '')" 2>/dev/null || echo "")"`,
      `  if [ -z "$HASH" ]; then warn "plugin not found: $NAME"; continue; fi`,
      `  curl -fsSL "https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/$HASH.zip" -o /tmp/decky-plugin.zip && \\`,
      // extract as root (the plugins dir is root-owned); chown back to deck after.
      `    sudo python3 -m zipfile -e /tmp/decky-plugin.zip "$HOME/homebrew/plugins/" && ok "plugin: $NAME" || warn "plugin failed: $NAME"`,
      `done`,
      `rm -f /tmp/decky-plugin.zip`,
      `sudo chown -R "$USER:$USER" "$HOME/homebrew/plugins" 2>/dev/null || true`,
      `sudo systemctl restart plugin_loader 2>/dev/null || true`,
    );
  }
  lines.push(`ok "decky ready (restart Steam to see it)"`);
  return lines.join("\n");
}

function protonBlock(cfg: DeckConfig): string {
  const lines: string[] = [];
  if (cfg.proton.protonUpQt || cfg.proton.protontricks || cfg.proton.ge)
    lines.push(`say "Proton tools"`);
  if (cfg.proton.protonUpQt) lines.push(fpInstall("net.davidotek.pupgui2"));
  if (cfg.proton.protontricks) lines.push(fpInstall("com.github.Matoking.protontricks"));
  if (cfg.proton.ge) {
    lines.push(
      `say "Installing latest Proton-GE"`,
      `install -d "$HOME/.steam/root/compatibilitytools.d"`,
      // The Deck/Ally are x86_64; GE-Proton now also ships an aarch64 tarball, so
      // exclude ARM builds or we grab the wrong arch (caught on hardware, 29 Jun).
      `GE_URL="$(curl -fsSL https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | python3 -c "import sys,json; d=json.load(sys.stdin); print(next((a['browser_download_url'] for a in d.get('assets',[]) if a['name'].endswith('.tar.gz') and 'aarch64' not in a['name'] and 'arm64' not in a['name']),''))" 2>/dev/null)"`,
      `if [ -n "$GE_URL" ]; then`,
      `  curl -fsSL "$GE_URL" -o /tmp/proton-ge.tar.gz && \\`,
      `    tar -xzf /tmp/proton-ge.tar.gz -C "$HOME/.steam/root/compatibilitytools.d/" && ok "Proton-GE installed" || warn "Proton-GE extract failed"`,
      `  rm -f /tmp/proton-ge.tar.gz`,
      `else warn "Proton-GE: use ProtonUp-Qt (release lookup failed)"; fi`,
    );
  }
  return lines.join("\n");
}

function emudeckBlock(cfg: DeckConfig): string {
  if (!cfg.emudeck) return "";
  // auto/internal → ~/Emulation; sdcard → the first SD mount if present.
  const path =
    cfg.emulationStorage === "sdcard" ? `\${SDCARD:-$HOME/Emulation}` : `$HOME/Emulation`;
  return `say "Staging EmuDeck"
SDCARD="$(ls -d /run/media/*/* 2>/dev/null | head -1)"
EMU="${path}"
for d in roms bios saves states; do install -d "$EMU/$d"; done
install -d "$HOME/Desktop"
curl -fsSL https://www.emudeck.com/EmuDeck.desktop -o "$HOME/Desktop/EmuDeck.desktop" && chmod +x "$HOME/Desktop/EmuDeck.desktop" || warn "EmuDeck download failed"
ok "EmuDeck staged at $EMU — run the wizard from Desktop"`;
}

function streamingBlock(cfg: DeckConfig): string {
  const lines: string[] = [];
  if (cfg.sunshine || cfg.vnc) lines.push(`say "Streaming / remote"`);
  if (cfg.sunshine) lines.push(fpInstall("dev.lizardbyte.app.Sunshine"));
  if (cfg.vnc) lines.push(fpInstall("org.tigervnc.vncviewer"));
  return lines.join("\n");
}

function tailscaleBlock(cfg: DeckConfig): string {
  if (!cfg.tailscale) return "";
  return `say "Installing Tailscale"
if ! command -v tailscale >/dev/null 2>&1; then
  (
    trap 'sudo steamos-readonly enable 2>/dev/null || true' EXIT
    sudo steamos-readonly disable 2>/dev/null || true
    curl -fsSL https://tailscale.com/install.sh | sh || warn "tailscale install failed"
  )
fi
sudo systemctl enable --now tailscaled 2>/dev/null || true
ok "Tailscale installed — run 'tailscale up' to log in"`;
}

function waydroidBlock(cfg: DeckConfig): string {
  if (!cfg.waydroid) return "";
  return `say "Staging Waydroid installer"
install -d "$HOME/Applications" "$HOME/Desktop"
if [ ! -x /usr/bin/waydroid ]; then
  git clone --depth 1 https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer.git "$HOME/Applications/SteamOS-Waydroid-Installer" 2>/dev/null || (cd "$HOME/Applications/SteamOS-Waydroid-Installer" && git pull) || warn "waydroid clone failed"
  cat > "$HOME/Desktop/Waydroid Installer.desktop" <<'BOOTIBLE_WD'
[Desktop Entry]
Name=Waydroid Installer
Exec=$HOME/Applications/SteamOS-Waydroid-Installer/steamos-waydroid-installer.sh
Terminal=true
Type=Application
Categories=System;
BOOTIBLE_WD
  chmod +x "$HOME/Desktop/Waydroid Installer.desktop"
fi
ok "Waydroid installer staged — run it from Desktop"`;
}

function stickdeckBlock(cfg: DeckConfig): string {
  if (!cfg.stickdeck) return "";
  return `say "Installing StickDeck"
install -d "$HOME/Applications" "$HOME/Desktop"
SD_URL="$(curl -fsSL https://api.github.com/repos/DiscreteTom/stickdeck-rs/releases/latest | python3 -c "import sys,json; d=json.load(sys.stdin); print(next((a['browser_download_url'] for a in d.get('assets',[]) if 'linux' in a['name'].lower()),''))" 2>/dev/null)"
if [ -n "$SD_URL" ]; then
  curl -fsSL "$SD_URL" -o /tmp/stickdeck.tar.gz && tar -xzf /tmp/stickdeck.tar.gz -C "$HOME/Applications/" && ok "StickDeck installed" || warn "StickDeck extract failed"
  rm -f /tmp/stickdeck.tar.gz
  cat > "$HOME/Desktop/StickDeck.desktop" <<'BOOTIBLE_SD'
[Desktop Entry]
Name=StickDeck
Exec=$HOME/Applications/stickdeck
Terminal=true
Type=Application
Categories=Game;Utility;
BOOTIBLE_SD
  chmod +x "$HOME/Desktop/StickDeck.desktop"
else warn "StickDeck: release lookup failed"; fi`;
}

function passwordManagerBlock(cfg: DeckConfig): string {
  const pms = passwordManagers(cfg.passwordManagers.managers);
  if (pms.length === 0) return "";

  if (cfg.passwordManagers.method === "flatpak") {
    const lines = [`say "Password managers (Flatpak)"`];
    for (const pm of pms) {
      lines.push(
        pm.flatpakIsRef
          ? `flatpak install --user --noninteractive ${pm.flatpak} || warn "failed: ${pm.id}"`
          : fpInstall(pm.flatpak),
      );
    }
    return lines.join("\n");
  }

  // Distrobox: full-feature native installs in an Arch container.
  const lines = [
    `say "Password managers (Distrobox Arch container)"`,
    `if command -v distrobox >/dev/null 2>&1; then`,
    `  distrobox list --no-color 2>/dev/null | grep -q '| arch ' || distrobox create -i archlinux:latest -n arch --yes`,
    `  distrobox enter arch -- sudo pacman -S --needed --noconfirm base-devel git || warn "base-devel failed"`,
    `  distrobox enter arch -- bash -c 'command -v yay >/dev/null || (git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin && cd /tmp/yay-bin && makepkg -si --noconfirm)' || warn "yay failed"`,
  ];
  for (const pm of pms) {
    const inst = pm.aur ? `yay -S --noconfirm ${pm.pkg}` : `sudo pacman -S --noconfirm ${pm.pkg}`;
    lines.push(
      `  distrobox enter arch -- ${inst} || warn "pm failed: ${pm.id}"`,
      `  distrobox enter arch -- distrobox-export --app ${pm.bin} 2>/dev/null || true`,
    );
  }
  lines.push(`else warn "distrobox not found — skipping password managers"; fi`);
  return lines.join("\n");
}

export function generateDeckProvision(input: Partial<DeckConfig>): string {
  const cfg = normalizeDeckConfig(input);
  const blocks: string[] = [HEADER];

  if (cfg.createSnapshot) blocks.push(SNAPSHOT);
  if (cfg.hostname) {
    blocks.push(`say "Setting hostname ${cfg.hostname}"
sudo hostnamectl set-hostname ${JSON.stringify(cfg.hostname)}`);
  }
  blocks.push(FLATHUB);

  for (const block of [
    flatpakBlock(cfg),
    deckyBlock(cfg),
    protonBlock(cfg),
    emudeckBlock(cfg),
    streamingBlock(cfg),
    tailscaleBlock(cfg),
    sshBlock(cfg),
    passwordManagerBlock(cfg),
    stickdeckBlock(cfg),
    waydroidBlock(cfg),
  ]) {
    if (block) blocks.push(block);
  }

  blocks.push(`say "Done. Restart to Gaming Mode to see your apps + Decky."`);
  return `${blocks.join("\n\n")}\n`;
}
